### ISSUE TITLE
Language Localization Support

### ISSUE THREAD

**Issue by spiriapbergeron** [zhanghai/ComposePreference#1]
How would we support different languages?

In the examples provided, titles and summaries are hard-coded. "That's ok" in the sense that before passing those strings to the composable, we can get the localized versions of the title and summary. 

But there seems to be somekind of missing functionality if we want to display a language-localized version of a selected choice from a single-from-list, or multi-from-list preference. Indeed, if my choices are "1", "2", "3" I will want to persist them as such in SharedPreferences, but in terms of display, I could want them as words in english ("one", "two", "three") or in french ("un", "deux", "trois"), etc. There seems to be something missing to let the library show the localized versions of the single-or-multi choices.

**Comment by zhanghai** [comment]
There is a `valueToText` lambda parameter for `ListPreference` and you should transform your language-neutral preference value into the display text in the device's current language.

**Comment by spiriapbergeron** [comment]
Thank you!
