### ISSUE TITLE
parameter enabled needs {}

### ISSUE THREAD

**Issue by obama** [zhanghai/ComposePreference#10]
i wanted to test the "enabled" parameter but i need to pass the value oddly wrapped with { }, else i get a type mismatch.
Is that intended?

## Expected Behavior
checkboxPreference(
                enabled = false ,
                key = "checkbox_preference",
                defaultValue = false,
                title = { Text(text = "Checkbox preference") },
                summary = { Text(text = if (it) "On" else "Off") },
            )

## Actual Behavior
checkboxPreference(
                enabled = { false },
                key = "checkbox_preference",
                defaultValue = false,
                title = { Text(text = "Checkbox preference") },
                summary = { Text(text = if (it) "On" else "Off") },
            )

**Comment by zhanghai** [comment]
Yes, because most parameters allows you to provide the value based on the checked state of the checkbox, `enabled` is just one such parameter.
