### ISSUE TITLE
Request for onCheckedChange Callback for twoTargetSwitchPreference and SwitchPreference

### ISSUE THREAD

**Issue by ByteFlipper-58** [zhanghai/ComposePreference#13]
#### Description

Currently, the `twoTargetSwitchPreference` and `SwitchPreference` implementations do not provide a way to handle state changes directly through a callback. This limits the ability to save changes immediately upon switching, as users need to click on the view to apply the change, rather than just toggling the switch.

#### Problem

In the existing implementation, saving the state upon switching requires handling the `onClick` event and manually updating the preference. This can be cumbersome and doesn't align with typical user expectations for switch behavior. An `onCheckedChange` callback would allow for a more straightforward and intuitive way to handle state changes.

#### Proposed Solution

Add an `onCheckedChange` parameter to both `twoTargetSwitchPreference` and `SwitchPreference` to handle state changes directly when the switch is toggled.

Here is an example of how this could be implemented:

```kotlin
twoTargetSwitchPreference(
    key = "dynamic_colors",
    defaultValue = false,
    title = { isChecked -> 
        Text(if (isChecked) "Dynamic Colors" else "Dynamic Colors") 
    },
    icon = { Icon(imageVector = Icons.Outlined.Info, contentDescription = null) },
    summary = { isChecked -> 
        Text(if (isChecked) "Dynamic colors are currently enabled." else "Dynamic colors are currently disabled.") 
    },
    onCheckedChange = { isChecked -> 
        switchChecked = isChecked
        saveDynamicColorPreference(context, isChecked)
    }
)
```

Thank you for considering this enhancement. It would greatly improve the user experience and simplify preference management.

**Comment by zhanghai** [comment]
Isn't there already the API that takes `onValueChange`?

```kotlin
@Composable
fun SwitchPreference(
    value: Boolean,
    onValueChange: (Boolean) -> Unit,
    title: @Composable () -> Unit,
    modifier: Modifier = Modifier,
    enabled: Boolean = true,
    icon: @Composable (() -> Unit)? = null,
    summary: @Composable (() -> Unit)? = null,
) 
```
