### ISSUE TITLE
How to get the defaultValue 

### ISSUE THREAD

**Issue by 64ArthurAraujo** [zhanghai/ComposePreference#14]
If i have a fresh installation of the app and try to get any of its preferences, "language" in this case it will return null by default
```kotlin
              listPreference(
                    key = "language",
                    defaultValue = "ja",
                    values = listOf(
                        "pt",
                        "ja",
                        "en"
                    ),
                    title = { Text(text = "Learning language") },
                    summary = { Text(text = "The language that you want to learn: $it") },
                    icon = {
                        Icon(
                            imageVector = Icons.Outlined.Translate,
                            contentDescription = null
                        )
                    },
                    type = ListPreferenceType.ALERT_DIALOG
                )
                Log.i("Settings", preferences.get<String>("language").toString())
                if (preferences.get<String>("language") == "ja") {
                    switchPreference(
                        key = "filter_romanizations",
                        defaultValue = true,
                        title = { Text(text = "Filter romanizations") },
                        icon = {
                            Icon(
                                imageVector = Icons.Outlined.ShortText,
                                contentDescription = null
                            )
                        },
                        summary = { Text(text = "Attempts to remove romanizations from lyrics of non alphabetic languages") }
                    )
                }
```
![image](https://github.com/user-attachments/assets/b80b766d-577d-4a79-bdee-e30ddc41258f)
(should be showing the switch preference but `preferences.get<String>("language")` returned null)

___

it will only show if i click the preference and set to "ja" manually, is there a way to make defaultValue the actual default value and not only visually so i don't have to check for null everytime i want to use the preference? Thanks in advance.

## Specifications

- Version: v1.1.1
- Platform: Android

**Comment by zhanghai** [comment]
The library is not mandating a way for you to store your default value so that's entirely up to you. Since you are manually passing in the default value for your preference composables, you need to manually do that for your preferences.get() calls as well, e.g. with the `?:` operator (it returns `null` when nothing has been set). You may also want to store your default values somewhere in order to avoid repetition but as mentioned earlier that's entirely up to you.
