### ISSUE TITLE
Feature request: Expose onCheckedChange for SwitchPreference

### ISSUE THREAD

**Issue by pierredelisle** [zhanghai/ComposePreference#2]
We have the following use case for SwitchPreference:
When the switch is clicked (value changes), we display a dialog explaining that the preference change will only take effect when the app exits and re-enters the foreground state.

If SwitchPreference supported "onCheckedChange", we could then support showing a Dialog to provide that information to the user.

Thanks!

**Comment by zhanghai** [comment]
You can use the `SwitchPreference` overload that allows you to pass in your own `onValueChanged`. You may need to duplicate some code from the other easier-to-use overloads, but that's the trade-off I had to take between easy-to-use and extensibility and the reason I provided the three overloads :P

https://github.com/zhanghai/ComposePreference/blob/24c035bac7765cbf52214bcbb0f10d331c429638/library/src/main/java/me/zhanghai/compose/preference/SwitchPreference.kt#L85-L94

**Comment by pierredelisle** [comment]
This works great! Thanks for the clarification, all good!
